#ifndef ERROR_HPP
#define ERROR_HPP

#include "Server.hpp"

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NOTREGISTERED 451
#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTERED 462
#define ERR_PASSWDMISMATCH 464
#define ERR_BADCHANNELKEY 475
#define ERR_BADCHANMASK 476

#endif